:markup-in-source: verbatim,attributes,quotes

= Bookbag Demo Development

Bookbag development is best suited for work on an OpenShift cluster.
Any recent version of OpenShift is suitable.
This demo was developed using a local development environment with https://developers.redhat.com/products/codeready-containers/overview[Red Hat CodeReady Containers].

== Build

Process and apply the OpenShift build template:

```
oc process -f build-template.yaml | oc apply -f -
```

Make edits as desired to local source, then build:

```
oc start-build bookbag --wait --follow --from-dir=.
```

Process and apply deploy template, setting `CONSOLE_IMAGE` to match the expected OpenShift version:

```
oc process -f deploy-template.yaml \
-p CONSOLE_IMAGE=quay.io/openshift/origin-console:$(oc version -o json | jq '.openshiftVersion' -r | sed 's/\.[0-9]*$//') \
-p WORKSHOP_VARS=$( cat workshop-vars.json ) \
| oc apply -f -
```

The deploy template includes a DeploymentConfig with an image change trigger so that it will automatically redeploy on build completion.


=== Customizing Bookbag's Layout

. By default Bookbag creates three frames: Lab instructions on the left and a terminal windows on the right.
If you want to change the number of terminal windows, change the `TERMINAL_TAB` environment variable in the
`envvars/gateway.sh` container to the following:
+
* `split` split for two vertitically stacked terminals
* `split/2` split twice for three vertitically stacked terminals

. If your lab content includes slides then simply add your slides HTML into the directory `workshop/slides/`.

. If you are not using the OpenShift terminal or slides then you may wish to only include the workshop instructions.
This may be done by setting `DEFAULT_PAGE="workshop"` in `envvars/gateway.sh`.

== Customizing Lab Instructions for Bookbag

Bookbag accepts lab instructions written in Asciidoc or Markdown although in Red Hat Asciidoc is considered the standard.
When editing your instructions for Bookbag some Asciidoc elements might be helpful:

* You can use environment variables throughout the text to provide users with lab-specific information such as
GUID, user credentials, URLs, etc.
* You can use font formatting such as *bold*, _italic_, etc. in command line and code examples.
For example you can use bold font for commands that the user should input on the keyboard, 
italic for parameters that should be replaced, etc.
You can make certain parts of the output bold to attract attention to the changes.

=== AgnosticD User Info in Acsiidoc

Bookbag pods will be deployed and configured so that information set by `agnosticd_user_info` when provisioning the lab is accessible within the content as macros.
In production your bookbag pods will be deployed for you with these settings.
During content development you will likely want to pass thes yourself.

All lab environments have a variable, `guid` set.
Single-user lab environments also have `user_info_messages` set, containing any messages passed with `agnosticd_user_info`, concatenated into a string with line breaks.
For multi-user lab environments, the variable `user` may be used to get the user name and `user_info_messages` is not available.

You can pass environment variable to the Bookbag container and then use them in lab instructions.
For example, instead of telling the user: "Use this URL and don't forget to replace 'GUID' with your actual GUID"
you can pass the actual GUID to the Bookbag container and create a URL that can be copied and pasted without any changes.

. Create a file called `workshop-vars.js` and define your variables like this for a single-user lab environment:
+
----
{
    "guid": "acdc",
    "user_info_messages": "hello\nworld\n",
    "some_custom_var": "example"
}
----
+
Or if developing for a multi-user lab environment:
+
----
{
    "guid": "acdc",
    "user": "student1",
    "some_custom_var": "example"
}
----

. In the beginning of each of your Asciidoc files include these variables and define Asciidoc's attributes 
("attributes" is the Asciidoc's word for variables). Here is the example:
----
:USER_GUID: %guid%
:USERNAME: %user%
:CUSTOM_VAR: %some_custom_var%
----

. Use those variables in Asciidoc files like this: `You username for this lab is {USERNAME}`. 
Avoid mixing environment variables you use in shell commands and variables you use in Asciidoc text.
For example, you might use `${GUID}` in your shell commands--in this case use `{USER_GUID}` in
the text.

. You may want to use a multi-line variable such as output of the deployment command with 
user information. The variable `user_info_messages` in the example above havs multi-line content.
In this case use the `[%hardbreaks]` directive to preserve formatting, like this:
+
----
Here are your informational messages:

[%hardbreaks]
%user_info_messages%
----

. Use the following command to deploy the image and pass the variables:
+
[source,subs="{markup-in-source}"]
----
$ *oc process -f deploy-template.yaml -p WORKSHOP_VARS="$(cat workshop-vars.json)" | oc apply -f -*
----

=== Text formatting in preformatted parts

If you want to use text formatting in command line or source code examples, use the following:

. Add this line at the top of your Asciidoc file:
+
----
:markup-in-source: verbatim,attributes,quotes
----

. Format your command line or source code blocks the following way:
+
------
[source,subs="{markup-in-source}"]
----
$ *oc get pods*
NAME                           READY   STATUS    RESTARTS   AGE
bookbag-005-5ffcccf9cf-584rt   2/2     Running   0          21h
----
------
+
It will look like this:
+
[source,subs="{markup-in-source}"]
----
$ *oc get pods*
NAME                           READY   STATUS    RESTARTS   AGE
bookbag-005-5ffcccf9cf-584rt   2/2     Running   0          21h
----


It is recommended to use a bold font to distinguish the command user is expected to type on the keyboard
from its output.
Also, place a dollar sign prompt `$` in the beginning of the line. 
If the command should be run as root, place a hash `#`.

== If you Deploy Homeroom Directly from Agnosticd

If you deploy your own openshift-homeroom lab interface directly from your AgnosticD config or workload then use the `agnosticd_user_info` ansible module to set `openshift_homeroom_url`.
We will use this variable to direct students to your openshift-homeroom workshop lab interface.

For example, if your AgnosticD configuration provisions a single lab environment to be used for a single student then you can set `openshift_homeroom_url` with:

----
  - name: Print User Information for each User
    agnosticd_user_info:
      data:
        openshift_homeroom_url: https://{{ openshift_homeroom_route_hostname }}/
----

If your AgnosticD configration deploys infrastructure for several students then set `openshift_homeroom_url` for each user:

----
  - name: Print User Information for each User
    agnosticd_user_info:
      user: "{{ ocp4_idm_htpasswd_user_base }}{{ n }}"
      data:
        openshift_homeroom_url: https://student-{{ n }}.{{ openshift_homeroom_route_domain }}/
    loop: "{{ range(1, 1 + ocp4_idm_htpasswd_user_count | int) | list }}"
    loop_control:
      loop_var: n
----

## Local Development


----
podman build -t bookbag .

podman run -ti -p 8080:10080 \
    -v $(pwd)/workshop/:/opt/app-root/workshop/:z \
    -v $(pwd)/envvars/:/opt/app-root/envvars/:z \
    -e WORKSHOP_VARS="$(cat workshop-vars.json )" \
    -e CLUSTER_SUBDOMAIN=$(oc get ingresscontroller/default -n openshift-ingress-operator -o jsonpath="{.status.domain}") \
    --rm bookbag

open http://localhost:8008/workshop
----


## Screen recording & Gif

----
WINDOW=$(swaymsg -t get_tree | \
    jq -r '..
        | select(.pid? and .visible?)
        | "\(.rect.x+.current_border_width),\(.rect.y+.current_border_width) \(.rect.width-(.current_border_width*2))x\(.rect.height-(.current_border_width*2))"
    ' | slurp)
    
wf-recorder -g "$WINDOW" -f out.mkv 
  -t 3 \

ffmpeg \
  -ss 00:00:00.000 \
  -i create-pipeline.mkv \
  -vf "fps=10,scale=1024:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
  -loop 1 \
  create-pipeline.mkv.gif

----
