:GUID: %guid%
:APPS: %cluster_subdomain%
:USER: %user%
:PASSWORD: %password%
:openshift_console_url: %openshift_console_url%
:user: %user%
:password: %password%

:REPO: https://raw.githubusercontent.com/sa-mw-dach/opentour-2022-servicemesh/main

:markup-in-source: verbatim,attributes,quotes
:source-highlighter: rouge

== Service Mesh


=== Open OpenShift Console

https://console-openshift-console.{APPS}

[%autowidth]
|===
h|Select Project|`{USER}-service-mesh-system`
|===

Check the operators installed in the Admin perspective, Operators. All Service Mesh related Operators should be there and ready.

=== Project files on Github

You can find all project files on Github:

https://github.com/sa-mw-dach/opentour-2022-servicemesh.git

But you don't need to clone the repo, you can apply the files directly to your OpenShift cluster.

=== Deploy the sample apps

First, switch to the apps project:
[source,subs="attributes"]
```
oc project {USER}-service-mesh-app
```

Then apply the deployment files for the apps:

[source,subs="attributes"]
```
oc create -f {REPO}/kubernetes/a-deploy.yml
oc create -f {REPO}/kubernetes/b-deploy.yml
oc create -f {REPO}/kubernetes/c-v1-deploy.yml
oc create -f {REPO}/kubernetes/c-v2-deploy.yml
```

Check the pods - all pods should be running and you should see in the READY column "2/2". Why 2? In the pod are 2 containers - one for the app and one for the Envoy Sidecar.

=== Create a Gateway for Ingress

Now we create a Gateway and expose our service-a.

[source,subs="attributes"]
```
oc create -f oc create -f {REPO}/kubernetes/gateway.yml
oc get route istio-ingressgateway -n {USER}-service-mesh-system

GATEWAY=....
curl $GATEWAY/service-a
```

If the services respond correctly, continue.

=== Canary Releases

[source,subs="attributes"]
```
oc create -f {REPO}/kubernetes/destination-rules.yml
```

Open a second terminal and run:
```
ROUTE=...
while true; do curl $ROUTE/service-a; sleep 0.5; done
```

Now in your first terminal apply the files for the Canary Deployment:

[source,subs="attributes"]
```
oc create -f {REPO}/kubernetes/canary/1-vs-v1.yml
oc replace -f {REPO}/kubernetes/canary/2-vs-v1_and_v2_90_10.yml
oc replace -f {REPO}/kubernetes/canary/3-vs-v1_and_v2_50_50.yml
oc replace -f {REPO}/kubernetes/canary/4-vs-v2.yml
```

Check Kiali and Jaeger, you can open these from OpenShift Console (Networing Routes).

=== Circuit Breaker and Retry

Let the terminal with the curl loop running or open a new one:
```
ROUTE=...
while true; do curl $ROUTE/service-a; sleep 0.5; done
```

[source,subs="attributes"]
```
oc scale deploy/service-c-v1 --replicas 0
oc scale deploy/service-c-v2 --replicas 2
oc replace -f {REPO}/kubernetes/circuit-breaker/1-vs.yml
```

Now connect to service-c and let it crash... in a separate terminal, run

```
oc get pod
POD_NAME=....
oc port-forward pod/$POD_NAME 8080:8080
curl localhost:8080/crash
```

See what happens in the terminal with the curl loop.

Now apply the Circuit Breaker (check what happens), then the Retry policy.

[source,subs="attributes"]
```
oc replace -f {REPO}/kubernetes/circuit-breaker/2-destination-rules.yml
oc replace -f {REPO}/kubernetes/circuit-breaker/3-vs-retry.yml
```

Finally repair the crashed service:
```
curl localhost:8080/repair
```

After ~10 seconds the repaired pod gets traffic.


Congratulations, you made it!!
